### PR TITLE
Pure-Data finalization, Dropdown interactivity

### PR DESCRIPTION
**Pull request by MovementGH**
- Adds support for dragging atoms in a listbox (desktop and WebPdL2Ork)
- Adds support for "interactive" flag on dropdowns
- Removed check in tests that was ensuring that inlets don't forward messages (since they do now)
- Re-migrated documentation that was adapted for listbox issues (only found discrepancies in list-help.pd, let me know if you find any others that I missed)
- Fix costables being freed when they shouldn't (#58)

### CODE REVIEW

**Comment by pd-l2ork** [comment]
Fantastic work, William. Will start testing builds shortly.

**Comment by pd-l2ork** [comment]
BTW, did you also add exclusive option to the dropdown?

**Comment by MovementGH** [comment]
No, upon investigation there is no glist_grab in the drop-down, and no keyboard input is used, so it didn’t seem like it would do anything. Lmk if I’m missing something

**Comment by pd-l2ork** [comment]
Keys are used to navigate the dropdown menu once it is toggled by clicking on the object, so you could still use keys up/down/enter to pick options. So, exclusive still has a purpose (albeit limited one).

**Comment by MovementGH** [comment]
Interesting. I thought i remembered you doing that, but at least on macos the arrow keys didnt do anything for me when the drop-down is open. I will investigate further.

**Comment by pd-l2ork** [comment]
Maybe this is done entirely JS-side? I seem to remember tinkering a lot with this there. I recommend investigating pdgui.js.

**Comment by pd-l2ork** [comment]
Did a quick test. Dropdown's keyboard navigation is definitely on the JS side of things and is, by design, exclusive. No key presses are passed to pd-l2ork. I suppose to do this right we would want to first pass keys to the backend from JS and then also implement the exclusive option that could potentially block this behavior, thus making it compliant with other supported GUI objects.

**Pull request merged**
