### PR TITLE
PdWebParty work

### PR DESCRIPTION
**Pull request by MovementGH**
- Add support for Scope GUI Object
- Add support for preset nodes
- Fix invisible characters in L2Ork-Tweeter
- Fix more firefox mouse issues
- Fix keyboard events firing in wrong order
- Fix arrays not being antialiased

### CODE REVIEW

**Comment by MovementGH** [comment]
Let me know if you want anything different in the Scope changes. Also, these are the known issues with tweeter (let me know of others if you find any)

- Networking doesn't work
- Load session doesn't work (because opening a file picker isn't yet supported. Note: this is only for sessions. Loading presets and loops works great)
- Saving presets and loops doesn't work (Intentional now, since it would be writing to the servers file system, which is not allowed. In the future might want to allow saving to local filesystem and then loading from local filesystem)

All of the presets and loops that I tried seem to work as intended with the correct sounds

**Comment by MovementGH** [comment]
I also did the project renaming, but as that would make it harder to tell the diffs for these changes, I will submit that after this PR is finished. If you would like to look at the renaming changes, they are here:

https://github.com/pd-l2ork/pd-l2ork/compare/master...MovementGH:pd-l2ork:Project-Rename

**Comment by pd-l2ork** [comment]
Thank you, William. Did you test rebuilding desktop version of Scope~ to ensure nothing broke as a result of new additions?

**Comment by MovementGH** [comment]
> Thank you, William. Did you test rebuilding desktop version of Scope~ to ensure nothing broke as a result of new additions?

I will do that momentarily, have to go onto the other computer. Shouldn't affect it, as all of the changes are inside ifdefs, but will check real quick.

**Comment by MovementGH** [comment]
Builds fine and scope still works on desktop

**Comment by pd-l2ork** [comment]
Perfect, thanks!

**Pull request merged**
