### PR TITLE
File Dialogs, WebPdL2Ork improvements, Build fixes

### PR DESCRIPTION
**Pull request by MovementGH**
- New filedialog implementation.
   - Tested on Windows, MacOS, Linux.
   - Compiler flag available to revert to old implementation if issues are found (compile x_gui.c with -DUSE_NWJS_FILEDIALOGS)
- Copy/Paste support in WebPdL2Ork (paste only works on https)
- HTTPS support in WebPdL2Ork (documentation available in DOCUMENTATION.md)
- Support for building on Apple Silicon Macs
   - Known Issue: pdlua does not work. It builds but crashes upon load (specifically, it crashes on dlopen() inside system code. This call traces to line 275 of s_loader.c). I was unable to determine why this is, but I created a check in the makefile to exclude pdlua if building on an Apple Silicon Mac.
- Updated apt-get requirements list, some libraries listed do not exist, and some required libraries were not listed.
- Added a favicon to WebPdL2Ork
- Fixed a typo in the loading screen of WebPdL2Ork

### CODE REVIEW

**Comment by MovementGH** [comment]
Interesting fact, after getting an ARM build working on macos, it brought CPU usage of tweeter running canada-mid from 24% to 16%, a 50% improvement in performance.

**Comment by pd-l2ork** [comment]
Great job, William. A couple of questions:

1) what is the attempt to fix windows build? looks like additional flags that were never needed before.

2) updating library list removes some of the libraries that are necessary for certain externals. what version of Linux are you using and what was the reason for removing those? (additions are fine, as is replacement, but removal may be a problem)

3) pdlua may be a bug upstream with the external

4) what replaces filedialog_perform function? Is it declared elsewhere? There are potentially other places that call it and the should be grep-ed to make sure everything else will continue to work as expected

Once these are clarified, I will merge this. Thanks.

**Comment by MovementGH** [comment]
1. Those flags are for the file dialog C library. For some reason it has no dependancies on linux or macos, but those two libraries have to be linked on windows (they are shipped with windows, but not linked by default)

2. Ubuntu 24.04, those packages are unable to be found. I can add them back in, but I have to edit those out of my apt-get install command whenever testing on ubuntu.

4. filedialog_perform is a new function, it did not exist before. In fact, the entire filedialog class is new. No changes are required for objects that previously called nwjs's filedialog, as I simply modified that function to redirect those requests to my code (and if the compiler flag is set to use the nwjs filedialogs, my code will send the request back to nwjs). So, this is a drop in change, all objects that used the old filedialogs are automatically using the new ones, including openpanel, savepanel, several things in cyclone, etc.

**Comment by pd-l2ork** [comment]
Perfect, thank you. Please see my comments below.

> 2. Ubuntu 24.04, those packages are unable to be found. I can add them back in, but I have to edit those out of my apt-get install command whenever testing on ubuntu.

In this case because the libraries are still needed for the 22.04 Ubuntu release, I would add a comment saying the original dependencies are for Ubuntu 22.04, and then add a second version of dependencies for Ubuntu 24.04. it is also important to do a bit of googling to see what those libraries were replaced in the Ubuntu 24.04. They typically just get retitled. Without them, certain externals will cease to build correctly, potentially breaking existing patches. You should atill add additional libraries to the 22.04.

**Comment by MovementGH** [comment]
Found 2 of the 3 libraries under different names (which also happen to be their names for 22.04, so the change happened before that) and re-added them. The other one I was unable to find on 24.04, so I left a note that for earlier versions, install that library as well. It is some gnome configuration library, so possibly it is built in now? I didn't see a clear answer other than the fact that it doesn't exist in the repos any more.

**Comment by pd-l2ork** [comment]
Perfect, thank you, William.

**Pull request merged**
