### PR TITLE
New Implementation of disis_wiimote

### PR DESCRIPTION
**Pull request by MovementGH**
Replaced custom cwiid with xwiimote, and refactored disis_wiimote to be more modern and stable.

### CODE REVIEW

**Comment by pd-l2ork** [comment]
William, I am just seeing this one. Did I somehow fail to merge this one? Any chance you could update it to resolve conflicts, so that I can merge it, as well? Thanks.

**Comment by MovementGH** [comment]
Yeah guess it got missed. Resolved the conflicts.

**Comment by pd-l2ork** [comment]
Perfect, thanks!

**Comment by pd-l2ork** [comment]
BTW is xwiimote crossplatform, or Linux-only?

**Comment by MovementGH** [comment]
Linux only

**Pull request merged**
