### PR TITLE
PdWebParty Work

### PR DESCRIPTION
**Pull request by MovementGH**
- Parallelize loading of abstractions
- Allow shift-dragging sliders
- Allow shift-dragging knobs
- Build patch_name from disis
- Build iemlib
- Build iemgui
- Build iemguts
- Build pdcontainer
- Fix pdWebParty docker not building properly on a dirty tree
- Fix editing arrays on firefox
- Fix editing arrays on touch screen
- Fix autotune
- Fix errors from ggeeimage
- Fix errors from pddplink
- Fix antialiasing of knobs/bangs
- Fix onKeyUp behavior
- Fix infinite loop for infinite recursion of subpatches
- Fix legacy mouse objects in subpatches
- Fix arrays overlapping border
- Fix message not displaying on subpatches and abstractions

### CODE REVIEW

**Comment by pd-l2ork** [comment]
Hi William, thanks for this. I am not sure if the A_EMPTY replacement is a good idea. Wouldn't it be better to check if the function ever gets called with a deffloat (or if it uses float at all) and then replace A_DEFFLOAT with A_NULL, as needed?

**Comment by MovementGH** [comment]
Agreed. Those functions do not take any arguments other than their class reference, so A_NULL should be the flag on both desktop and emscripten. Really, if it were consistent with other externals, there shouldn't even be an A_NULL, just the 0 to mark the end of the arguments, however this does not build (I think it has something to do with it being c++, not c). However, I didn't want to introduce any changes to the desktop build, so that is why I made the ifdef for whether it is being built for emscripten. Changing it to A_NULL shouldn't make a difference, but I was following the better safe than sorry policy. If you are ok with changing it to A_NULL across the board, I can do that. Desktop pd-l2ork doesn't seem to care, but emscripten crashes when running those functions if the signatures don't match up perfectly.

**Comment by MovementGH** [comment]
Ran into DSP issues that I have traced back to this commit, will need to hold off until I can patch it

**Comment by MovementGH** [comment]
Turns out it wasn't DSP, it was just messages and their lack of wireless connections being a pain again. Anyway, its fixed now.

**Comment by pd-l2ork** [comment]
BTW -fsanitize-address is necessary for objects to retain their address, so that referencing objects based on their address works. This is something that made pd-web-party unusable, until I fixed this. Are you sure removing this is a good idea?

**Comment by pd-l2ork** [comment]
> Agreed. Those functions do not take any arguments other than their class reference, so A_NULL should be the flag on both desktop and emscripten. Really, if it were consistent with other externals, there shouldn't even be an A_NULL, just the 0 to mark the end of the arguments, however this does not build (I think it has something to do with it being c++, not c). However, I didn't want to introduce any changes to the desktop build, so that is why I made the ifdef for whether it is being built for emscripten. Changing it to A_NULL shouldn't make a difference, but I was following the better safe than sorry policy. If you are ok with changing it to A_NULL across the board, I can do that. Desktop pd-l2ork doesn't seem to care, but emscripten crashes when running those functions if the signatures don't match up perfectly.

So, I don't see any fixes for this in the merge request. Did I miss something?

**Comment by MovementGH** [comment]
> BTW -fsanitize-address is necessary for objects to retain their address, so that referencing objects based on their address works. This is something that made pd-web-party unusable, until I fixed this. Are you sure removing this is a good idea?

When that flag was enabled, pdcontainer does not work (I think because of how it manages memory it sets off some kind of alarm that that flag controls). When the flag is enabled and pdcontainer is built, the website immediately crashes upon load.

What are some of the issues you had with the flag disabled? I can test them and see if i can find a configuration that stops them from happening while allowing pdcontainer to run. I personally have not had any issues yet with that flag disabled.

**Comment by MovementGH** [comment]
> > Agreed. Those functions do not take any arguments other than their class reference, so A_NULL should be the flag on both desktop and emscripten. Really, if it were consistent with other externals, there shouldn't even be an A_NULL, just the 0 to mark the end of the arguments, however this does not build (I think it has something to do with it being c++, not c). However, I didn't want to introduce any changes to the desktop build, so that is why I made the ifdef for whether it is being built for emscripten. Changing it to A_NULL shouldn't make a difference, but I was following the better safe than sorry policy. If you are ok with changing it to A_NULL across the board, I can do that. Desktop pd-l2ork doesn't seem to care, but emscripten crashes when running those functions if the signatures don't match up perfectly.
> 
> Yes. please fix those, especially if the function arguments do not match the method declarations.

Ok, Will do

**Comment by pd-l2ork** [comment]
If pdcontainer needs it, we need to figure out why and whether we can build it without that flag. For me, nothing worked when I did not use this flag.

Best,

Ico
--
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Director, Human-Centered Design iPhD
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net
________________________________

**Comment by pd-l2ork** [comment]
Thanks for making requested updates. I will go ahead and commit this. We will need to thoroughly test this. I am mainly concerned with sanitize-address flag in the emscripten/Makefile. More soon...

**Pull request merged**
