### PR TITLE
WebPdL2Ork Bugfixes (Last batch for now)

### PR DESCRIPTION
**Pull request by MovementGH**
- Fixes mismatched function error in pluton on WebPdL2Ork
- Fixes connection errors in pluton in WebPdL2Ork
- Shows touch keyboard on mobile devices when focusing atom or nbx on WebPdL2Ork

This should be all the remaining issues with WebPdL2Ork that are currently known.

The errors popping up about "unknown object" *seem* to be not an issue, I hooked up a print to one of those and sending messages to it works, and the loadbang happens *after* all of the errors. So, pending a functionality issue coming up (which won't be able to investigate until the externals are gotten for that patch) I don't think its an issue.

You don't want to know how long it took to figure out that the bang object was the one that was broken just to change about 10 lines in its source... I am considering investigating a way to find issues like that at compile time and block compilation if there are any mismatched functions.

### CODE REVIEW

**Comment by MovementGH** [comment]
^ Heres the keyboard in action

**Comment by pd-l2ork** [comment]
Fantastic work, William!

**Comment by pd-l2ork** [comment]
Tried adding text in Tweeter chat and session load atom and it did not work. It focused below the entire patch and nothing got entered. This is on Android BTW.

**Comment by MovementGH** [comment]
I’ll have to figure out getting an android vm running then, it works on iOS (though everything on iOS is safari, even chrome and firefox are safari internally, so it is most likely that it works on safari only then iOS only)

Thanks for the heads up

**Comment by MovementGH** [comment]
Still waiting on apple to fix the issue where after refreshing the page a few times everything freezes… memory lesks galore

**Comment by pd-l2ork** [comment]
> I’ll have to figure out getting an android vm running then, it works on iOS (though everything on iOS is safari, even chrome and firefox are safari internally, so it is most likely that it works on safari only then iOS only)
> 
> Thanks for the heads up

No problem. You could try installing Chrome on iOS and checking if you encounter the same issue. It could be Chrome-centric.

**Comment by pd-l2ork** [comment]
> Still waiting on apple to fix the issue where after refreshing the page a few times everything freezes… memory lesks galore

Yeah, this is a long-standing issue that affects (AFAIK) both vanilla and pd-l2ork. I imagine emscripten may make things even more memory-intensive. Please note I announced the project last evening and we have had quite a bit of traffic, so that could be also contributing. I would make this low priority at this point.

**Comment by MovementGH** [comment]
> > Still waiting on apple to fix the issue where after refreshing the page a few times everything freezes… memory lesks galore
> 
> Yeah, this is a long-standing issue that affects (AFAIK) both vanilla and pd-l2ork. I imagine emscripten may make things even more memory-intensive. Please note I announced the project last evening and we have had quite a bit of traffic, so that could be also contributing. I would make this low priority at this point.

This particular manifestation is specific to safari and i found documented issues from the basic emscripten template that this happens for all emscripten projects, safari just doesnt clean up after itself between page loads. Even if it was high priority theres nothing we can do.

**Comment by MovementGH** [comment]
> > I’ll have to figure out getting an android vm running then, it works on iOS (though everything on iOS is safari, even chrome and firefox are safari internally, so it is most likely that it works on safari only then iOS only)
> > Thanks for the heads up
> 
> No problem. You could try installing Chrome on iOS and checking if you encounter the same issue. It could be Chrome-centric.

Unfortunately, chrome on iOS is also safari (apple forces everyone to use WebKit for rendering on iOS). Good for consistency  on iOS, but impossible to test anything other than safari using an iOS device

**Comment by pd-l2ork** [comment]
I see. Any easy way to emulate android on iOS?

**Comment by MovementGH** [comment]
I have an android vm on my desktop computer that i use for some tasks, will have to test if that behaves similarly enough to a phone to reproduce the issue (it is x86 and i think it knows that it is being controlled by a mouse and keyboard not a touchscreen, so not sure if the keyboard will pop up at all)

Will look into it tomorrow after writing up my info for the report

**Comment by pd-l2ork** [comment]
Sounds good. Thanks.

**Pull request merged**
