### PR TITLE
PdWebParty Work

### PR DESCRIPTION
**Pull request by MovementGH**
- Fix sickle objects
- Fix some keyname events with wrong names (Shift and F1 instead of ShiftF1)
- Fix some text parsing issues
- Silence preset node errors
- Build zexy for pdWebParty

All disis demo patches should work fully on this commit (Please test in case I missed some functionality they are supposed to have)

As a side note, L2Ork Tweeter works (and no more load-time errors!) except for networking,  audio out, and presets (As in, you can select a tweeter using Shift+Function and play and put notes, they just don't make any noise)

### CODE REVIEW

**Comment by pd-l2ork** [comment]
Excellent work!

**Comment by pd-l2ork** [comment]
Do we need ifdefs in the two GUI objects, or could the same be used for both emscripten and C?

**Comment by MovementGH** [comment]
Not sure, and from the name of the functions it does seem like they should return something, but emscripten complains if they aren't void.

**Comment by pd-l2ork** [comment]
How about we then just make them void and be done with it, especially if they are not returning anything. Speaking of which, how is C compiling if they aren't returning anything?

**Comment by pd-l2ork** [comment]
Looks like it is defined as void in pd/src/g_text.c, so these should be simply made into void without any ifdefs. Would you please change this and then I will merge? Thank you.

**Pull request merged**
